services:
    segmentio.consumer.socket:
        class: Vouchedfor\SegmentIOBundle\Consumer\AbstractConsumer
        factory: [Vouchedfor\SegmentIOBundle\Consumer\ConsumerFactory, createConsumer]
        arguments:
            type: socket
            access_token: %segmentio.access_token%

    segmentio.consumer.batch:
        class: Vouchedfor\SegmentIOBundle\Consumer\AbstractConsumer
        factory: [Vouchedfor\SegmentIOBundle\Consumer\ConsumerFactory, createConsumer]
        arguments:
            type: batch
            access_token: %segmentio.access_token%

    segmentio.segment:
        class: Vouchedfor\SegmentIOBundle\Segment\Segment
        arguments:
            consumer: @segmentio.consumer.socket

    segmentio.batch:
        class: Vouchedfor\SegmentIOBundle\Segment\Segment
        arguments:
            consumer: @segmentio.consumer.batch
